#!/bin/bash

#check for argument and show usage 
if [ -z "$1" ]; then
  echo "Usage: $0 <filename>"
  exit 1
fi


# 1. Convert the semicolon separator to the  <tab> character [DONE]
# 2. Convert the Microsoft line endings to Unix line endings. [DONE]
# To verify: file <file_name>. CRLF in output means windows ending exists.
# 3. Change format of floating-point numbers to use ‘.’ rather than ‘,’ as the decimal point. [DONE]
# 4. Deal with non-ASCII characters by deleting them from the output. [DONE]
# For example CO2 in a game title is rendered as CO. (Hint: one way is to use the tr command.) 
# to verify compare cat bgg_dataset.txt | grep 272380 with ./preprocess bgg_dataset.txt | grep 272380 
# 5. While other empty cells can be ignored for now, new unique IDs need to be created for the 16 empty IDs. How you do this is up to you, but one way is to find the largest integer ID in the input file, and then continue numbering past that.

# convert semicolon to tab as delimiter, convert CRLF, convert '.' to ',', delete ASCII. Store to variable
cleaned=$(cat "$1" | tr ';' '\t' | tr -d '\r' | sed 's/\([0-9]\),\([0-9]\)/\1.\2/g' | tr -cd '\0-\177')

# Get highest value from first column
max_value=$(echo "$cleaned" | cut -f1 | grep -E '^[0-9]+$' | sort -n | tail -n 1 )
