#!/bin/bash

#check for argument and show usage 
if [ -z "$1" ]; then
  echo "Usage: $0 <filename>"
  exit 1
fi

# convert semicolon to tab as delimiter, convert CRLF, convert decimal, delete ASCII. Store to variable cleaned
cleaned=$(cat "$1" | tr ';' '\t' | tr -d '\r' | sed 's/\([0-9]\),\([0-9]\)/\1.\2/g' | tr -cd '\0-\177')
header=$(echo "$cleaned" | head -n 1)
data=$(echo "$cleaned" | tail -n +2)

# Get highest value from first column
max_id=$(echo "$cleaned" | cut -f1 | grep -E '^[0-9]+$' | sort -n | tail -n 1 )
next_id=$((max_id + 1))

# Process each line in the cleaned data
final=$(echo "$data" | while IFS=$'\t' read -r first_column rest; do
    #if [[ -z "$first_column" || ! "$first_column" =~ ^[0-9]+$ ]]; then
    if [[ ! "$first_column" =~ ^[0-9]+$ ]]; then
        echo -e "${next_id}\t$first_column\t$rest"
        next_id=$((next_id + 1))
    else
        echo -e "$first_column\t$rest"
    fi
done)

# Output final result
echo "$header"
echo "$final"